Cart and Wishlist Management
amantulsyan35/enkidu-ecommerce-react pull request #9
Opened 2022-03-26 15:34 UTC by amantulsyan35

2022-03-28 10:49 UTC, nikhiljugale007 reviewed
Added a few suggestions in the code.
Not able to add to products in wishlist and cart in preview.
Cart page is redirecting to checkout not sure it is intended or not.

2022-03-28 10:49 UTC, nikhiljugale007 commented on src/Pages/Checkout/index.js
> +        type: 'ADD_TO_CART',
Here your productDispatch type is ADD_TO_CART, while the function is to to decrement product quantity. It causing confusion what the function does.
You can use better naming convention here.
You can use something like SET_CART_LIST.

2022-03-28 10:49 UTC, nikhiljugale007 commented on src/Pages/Products/index.js
> +            { label: '1 stars & above', rateType: 1 },
Suggestion: you can extract rating and category arrays to separate files and map here.

2022-03-28 10:49 UTC, nikhiljugale007 commented on src/components/Navbar/index.js
> +            </Link>
Suggestion: You can use NavLink instead of Link here.

2022-03-28 12:48 UTC, Naman-Saxena1 requested changes
I tried creating an account and testing wishlist and cart functionality but after login was not able to do it, maybe you can cross-check that.

2022-03-28 12:48 UTC, Naman-Saxena1 commented on src/Pages/Checkout/index.js
> +      type: 'ADD_TO_CART',
Yeah, similar to what Nikhil mentioned, here your function is to removeFromCart and dispatch action type is ADD_TO_CART. Maybe you have not tested this yet.

2022-03-28 12:48 UTC, Naman-Saxena1 commented on src/context/product-context.js
> +          wishListed: !state.wishListed,
For a better codebase design, I separated wishlist and cart functionality in different files but I guess this is also fine. Plus if you make this change now, you will have to update at a lot of places.

2022-04-07 08:15 UTC, gouravmarch20 commented on src/Pages/Wishlist/index.js
> +      const response = await axios({
create a sperate folder  there use axios , & return backend response here . 

because as application grow it will be very easy to debug

2022-04-07 08:22 UTC, gouravmarch20 approved these changes
No major changes required  ,  just a suggestion avoid API hit directly in component  ==> create a separate folder to hit all URL & return api data to given component

2022-06-29 13:34 UTC, closed without merging